version: '2'

services:
  wikidb:
    image: mongo
    expose:
      - '27017'
    command: '--smallfiles --bind_ip wikidb'
    environment:
      - 'MONGO_LOG_DIR=/dev/null'
    volumes:
      - ./data/mongo:/data/db

  wiki:
    image: wiki:local-latest
    build:
      context: .
    links:
      - wikidb
    depends_on:
      - wikidb
    ports:
      - '3000:3000'
    # entrypoint: node wiki configure 3000
